services:
  server:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: ${PORT:-3000}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    volumes:
      - ./logs:/usr/src/app/logs:rw
      - ./uploads:/usr/src/app/uploads:rw
      - ./audiostream.db:/usr/src/app/audiostream.db:rw
    restart: unless-stopped