services:
  server:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: ${PORT:-3000}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN:-true}
      CORS_METHODS: ${CORS_METHODS:-*}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS:-*}
      CORS_EXPOSED_HEADERS: ${CORS_EXPOSED_HEADERS:-*}
      CORS_CREDENTIALS: ${CORS_CREDENTIALS:-true}
      CORS_MAX_AGE: ${CORS_MAX_AGE:-5}
      CORS_PREFLIGHT: ${CORS_PREFLIGHT:-true}
    volumes:
      - ./logs:/usr/src/app/logs:rw
      - ./uploads:/usr/src/app/uploads:rw
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: cadence
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d cadence"]
      interval: 5s
      timeout: 5s
      retries: 5
