services:
  server:
    build: .
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      PORT: ${PORT:-3000}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    volumes:
      - ./uploads:/usr/src/app/uploads:rw
      - ./audiostream.db:/usr/src/app/audiostream.db:rw
    restart: unless-stopped
